### ISSUE TITLE
Create project wiki

### ISSUE THREAD

**Issue by m-barnas** [m-barnas/ice-hockey-manager#2]
- [x] Create project wiki to publish description and other information about project.

Menu items inspiration:

- Home
- Documentation
  - UML diagrams
    - Use case
    - Design class
  - Rest API
- Authors

**Comment by Hathoriel** [comment]
I will do this task. What content do you want in menu item "For users"? In other menu items I know what I will add as content.

**Comment by m-barnas** [comment]
A really tempting description, so that user will immediately download the app. (Just kidding) What it important to say, the items should be rather an inspiration for you, feel free to add, remove or change them.

**Comment by m-barnas** [comment]
The first idea was to put there some background story, but you can omit this item for now. Background story can be in README.md file present in root directory of the repo.

**Comment by m-barnas** [comment]
The third point of my answer: The app is expected to be available online, so users are not going to visit our wiki. :(
So we can rename For developers to Documentation or as I said feel free to modify the menu :)

**Comment by m-barnas** [comment]
Sorry, you are right. Menu item "For users" does not make sense. Menu items inspiration is updated.
Feel free to modify it. Sub-items Use case and Design class you can leave empty, other team members will add their diagrams there. Sub-item Rest API you can leave empty or omit it for now.

**Comment by Hathoriel** [comment]
The wiki documentation is done except for UML diagrams. So I am waiting for them. Where should our colleagues add these diagrams? 
 
REST API will be omitted now until we have real REST API created by BE.

**Comment by m-barnas** [comment]
Ok, perfect! :) They will add them to the ice-hockey-manager/doc folder. The folder will be provided after my project-structure commit. Further information about using images from repo -> wiki, can be found [here](https://guides.github.com/features/mastering-markdown/), select **Examples/Images**.

p.s. I 've added mail addresses to the Authors page.
