### ISSUE TITLE
Create use case diagram

### ISSUE THREAD

**Issue by m-barnas** [m-barnas/ice-hockey-manager#3]
- [x] Create a new item in wiki: For developers / UML digrams / Use Case and publish your diagram.
- [x] Create use case diagram with at least two user roles.

**Comment by jakub-h** [comment]
@m-barnas @Hathoriel 

Please, check someone the Use case diagram. I added an actor Time, which starts 'Play the game' use case. 
The link on wiki must be updated after merging branch jhruska-milestone-1.

**Comment by m-barnas** [comment]
Super! I like an inheritance between a common user and admin and all functional requirements, hovewer, you may perhaps consider omitting Manager.scheduleGame and leaving the functionality on an exeternal system.

**Comment by jakub-h** [comment]
Done.
