### ISSUE TITLE
Create Team entity and Dao.

### ISSUE THREAD

**Issue by Hathoriel** [m-barnas/ice-hockey-manager#5]

**Comment by m-barnas** [comment]
Done by @Hathoriel.

**Comment by m-barnas** [comment]
- [x] Rename method finAll to findAll in TeamRepository, TeamDao and TeamDaoImpl
- [x] Use unidirectional one-to-one mapping for Team.humanPlayer

Note: Commit your changes after mvn clean install **success**.
